export { default as LoginPage } from './LoginPage';
export { default as AuthCallback } from './AuthCallback';
export { default as Dashboard } from './Dashboard';
export { default as AddQuestion } from './AddQuestion';
export { default as ViewQuestions } from './ViewQuestions';
export { default as QuestionDetail } from './QuestionDetail';
export { default as MySubmissions } from './MySubmissions';
export { default as EditQuestion } from './EditQuestion';
export { default as AdminPanel } from './AdminPanel';
